server:
  host: "0.0.0.0"        # Открытый для внешнего подключения хост
  port: 9080

database:
  url: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
  max_connections: 30
  max_idle_connections: 10
  migrations_dir: "file:///app/migrations"
  database_name: "postgres"

file_upload:
  upload_dir: "/app/uploads"
  static_dir: "/app/assets"

logging:
  level: "info"

python:
  interpreter: "/app/venv/bin/python"
  script_path: "/app/scripts/python_script.py"

  organization:
    default_inn: "7719034354"
    default_name: "КАЗЕННОЕ ПРЕДПРИЯТИЕ 'МОСКОВСКАЯ ЭНЕРГЕТИЧЕСКАЯ ДИРЕКЦИЯ'"
    default_inn_credit: "7719034354"
    default_name_credit: "КАЗЕННОЕ ПРЕДПРИЯТИЕ 'МОСКОВСКАЯ ЭНЕРГЕТИЧЕСКАЯ ДИРЕКЦИЯ'"